[package]
entrypoint = "run"

[dependencies]
"php/php-eh" = "=8.3.404-beta.4"
"wasmer/bash" = "*"
"wasmer/static-web-server" = "*"

[fs]
"/app" = "app"
"/db" = "db"
"/config" = "config"

[[command]]
name = "run"
module = "php/php-eh:php"
runner = "wasi"
[command.annotations.wasi]
main-args = [
    "-t", "/app",
    "-S", "0.0.0.0:8080",
    "-d", "memory_limit=256M",
    "-d", "max_execution_time=600",
    "-d", "max_input_time=600",
    "-d", "max_input_vars=4096",
    "-d", "upload_max_filesize=1024M",
    "-d", "post_max_size=1024M",
]